export const FETCH_ARTWORKS_START = 'FETCH_ARTWORKS_START';
export const FETCH_ARTWORKS_SUCCESS = 'FETCH_ARTWORKS_SUCCESS';
export const FETCH_ARTWORKS_FAIL = 'FETCH_ARTWORKS_FAIL';
export const ADD_ARTWORK_START = 'ADD_ARTWORK_START';
export const ADD_ARTWORK_SUCCESS = 'ADD_ARTWORK_SUCCESS';
export const ADD_ARTWORK_FAIL = 'ADD_ARTWORK_FAIL';
export const SEARCH_ARTWORK_START = 'SEARCH_ARTWORK_START';
export const SEARCH_ARTWORK_SUCCESS = 'SEARCH_ARTWORK_SUCCESS';
export const SEARCH_ARTWORK_FAIL = 'SEARCH_ARTWORK_FAIL';

export const FETCH_AESTHETES_START = 'FETCH_AESTHETES_START';
export const FETCH_AESTHETES_SUCCESS = 'FETCH_AESTHETES_SUCCESS';
export const FETCH_AESTHETES_FAIL = 'FETCH_AESTHETES_FAIL';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';

export const FETCH_ART_CATEGORIES_START = 'FETCH_ART_CATEGORIES_START';
export const FETCH_ART_CATEGORIES_SUCCESS = 'FETCH_ART_CATEGORIES_SUCCESS';
export const FETCH_ART_CATEGORIES_FAIL = 'FETCH_ART_CATEGORIES_FAIL';

