export const FETCH_ARTWORKS_START = 'FETCH_ARTWORKS_START';
export const FETCH_ARTWORKS_SUCCESS = 'FETCH_ARTWORKS_SUCCESS';
export const FETCH_ARTWORKS_FAIL = 'FETCH_ARTWORKS_FAIL';

export const FETCH_AESTHETES_START = 'FETCH_AESTHETES_START';
export const FETCH_AESTHETES_SUCCESS = 'FETCH_AESTHETES_SUCCESS';
export const FETCH_AESTHETES_FAIL = 'FETCH_AESTHETES_FAIL';

